insect:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
  # Effort Controllers ---------------------------------------
  l_f_hip_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: l_f_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_f_hip_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: r_f_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_b_hip_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: l_b_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_b_hip_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: r_b_hip_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_f_limb_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: l_f_limb_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_f_limb_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: r_f_limb_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_b_limb_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: l_b_limb_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_b_limb_joint_torque_controller:
    type: effort_controllers/JointEffortController
    joint: r_b_limb_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
