insect_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  l_f_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_f_motor_joint #check that motor joiint is use ot not not fix about what to define here
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_f_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: r_f_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_b_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_b_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_b_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: r_b_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_f_h_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_f_h_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_f_h_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: r_f_h_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_b_h_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_b_h_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_b_h_motor_joint_controller:
    type: effort_controllers/JointPositionController
    joint: r_b_h_motor_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
